### ISSUE TITLE
SENZING_EXIT_ON_THREAD_TERMINATION Not documented in Knowledge-base

### ISSUE THREAD

**Issue by yash078** [Senzing/redoer#392]
**What is the URL of the documentation?**

- https://github.com/Senzing/knowledge-base/blob/main/lists/environment-variables.md#senzing_exit_on_thread_termination
   
**What can be improved?**

The linked section doesn't exist.

**Additional context**

While running the Redoer in a docker container, I want to terminate the container after the redo queue is empty. I set this variable to True, but it doesn't seem to have an effect. The container continues to run. Am I missing anything here?

![image](https://github.com/Senzing/redoer/assets/43049879/d5b41e0c-8ac8-4181-b978-d1eedb183b0a)

**Comment by docktermj** [comment]
### Research

- https://github.com/Senzing/redoer/blob/a47ef6da63e44e521baa9048b5340076919e86fe/redoer.py#L2082
- https://github.com/Senzing/redoer/blob/a47ef6da63e44e521baa9048b5340076919e86fe/redoer.py#L2712
- https://github.com/Senzing/redoer/blob/a47ef6da63e44e521baa9048b5340076919e86fe/redoer.py#L2763

**Comment by docktermj** [comment]
@yash078 The `SENZING_EXIT_ON_THREAD_TERMINATION` variable isn't related to the redo queue being empty.  I apologize for not having it documented well.   Currently there is no "terminate when there aren't any redo records" option.  Mostly because it's possible for the redo queue to be empty momentarily as records are still being added to the system.

As seen in 

https://github.com/Senzing/redoer/blob/a47ef6da63e44e521baa9048b5340076919e86fe/redoer.py#L2761-L2788

Around line 2785, there's a moment when the redo queue is empty at which time the process sleeps and then revisits the queue.

The technique we've used in large systems is to scale up the number of redoers when the load is high and then let the system (e.g. Kubernetes, OpenShift, etc.) scale down the redoers to just 1 to handle any new records which may cause the generation of redo records.  In this case, it's the system (Kubernetes) that kills the redoers.  Naturally, the redoers may need to scale up again.   This was the goal of the current design of the redoer -- the "exterior" system manages the fleet of redoers.

**Comment by yash078** [comment]
Thanks @docktermj for the feedback.

Would there be an issue if I replace that line, 2785, with `sys.exit()` for our use case?

**Comment by docktermj** [comment]
@yash078   For your custom application, I believe that would work fine.  It look like `break` would exit the `while True:` loop.  That, in turn, would stop the execution of the for-loop.

**Comment by docktermj** [comment]
@yash078 And if you really want to kill it:

```python
sys.exit(0)
```

**Comment by docktermj** [comment]
Or

```python
os._exit(1)
```

Reference: https://stackoverflow.com/questions/9591350/what-is-difference-between-sys-exit0-and-os-exit0

**Comment by brianmacy** [comment]
Be careful with that solution.  The exit would abort any currently running redo and the break ignores the fact that any currently running redo may generate more redo.

Highly recommend switching to a much more simple redoer example (https://github.com/brianmacy/sz_simple_redoer).  In that one, you could just add a check when getRedoRecord() returns nothing that the futures are empty too... then exit.  That would cleanly get what you want.  There is a Java version (https://github.com/Sameroniwcheeze/sz_simple_redoer_java) if you prefer.

**Comment by brianmacy** [comment]
We encourage our employees to have developer code examples in their personal GitHubs (even our Quickstart for Docker points to nearly 100% non-senzing GitHub examples).  Keep in mind this is all Apache 2.0 licensed examples without warranty... so whether you get the github.com/senzing one or not, it has the same license.

**Comment by docktermj** [comment]
@yash078 Is there anything else we can do for you on this topic?


(If no response in a week, I'll go ahead and close this issue.  Feel free to open up issues in the future.)

**Comment by yash078** [comment]
I personally got the answer I was looking for. However, the missing documentation issue I reported here is still not resolved.

**Comment by docktermj** [comment]
@yash078 Right you are!   I just added documentation to https://github.com/Senzing/knowledge-base/blob/main/lists/environment-variables.md#senzing_exit_on_thread_termination

May I close this issue?  (or you can, too)
